name:  jrCMS

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # steps:
      # - name: Git checkout
      #    uses: actions/checkout@v2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test


  # strategy:
  #   matrix:
  #     node-version: [14.x, 16.x]
  #     mongodb-version: ['4','5']

